### PR TITLE
Add Environment::runWithStringResults to enable better Lua console REPL

### PR DESCRIPTION
**Pull request by GinjaNinja32**
There may be a better design here - happy to adjust if you have suggestions.

### CODE REVIEW

**Comment by daid** [comment]
Not a fan of so much extra code which is mostly duplicated with minor variations. I think the only thing you currently cannot do yet is the MULTIRET, the rest is sort of doable outside of SP changes.

**Comment by GinjaNinja32** [comment]
hmm. Might be able to merge the two paths into one with something like

```c++
Result<void> runStrings(code, name, callback) {
    return runImpl(code, name, [](firstResult) {
        // string code
    });
}
Result<T> runResult(code, name) {
    return runImpl(code, name, [](firstResult) {
        if (lua_gettop(L) < firstResult) {
            // no returned value, convert as if nil
        } else {
            // convert index `firstResult` as normal
        }
        // pop?
    });
}
Result<T> runImpl(code, name, std::function<Result<T>(int firstResult)> handleResults) {
    // MULTRET code through L86
    return handleResults(top - 1);
}
```

**Comment by daid** [comment]
https://github.com/daid/EmptyEpsilon/commit/183db32c0cb229809e2277e70dad27c8568990d2
https://github.com/daid/SeriousProton/commit/5ff9371ad9abc55de9094d9771a2210e0b87c267
This is my attempt in the ECS branch.

**Comment by GinjaNinja32** [comment]
that implementation looks good and does what I wanted from this :+1:

**Pull request closed without merging**
