### PR TITLE
allow to set arguments when calling a Lua function

### PR DESCRIPTION
**Pull request by czenker**
I tried to implement a way to set arguments when calling a Lua function. This would allow to create a more event based Lua API for Empty Epsilon, like callbacks if an artifact was picked up, an object was destroyed or a docking procedure finished.

Please review, because today was the first day just read any parts of Lua's C API and it was complex enough that I hope that I at least understood the important parts. Also I only got basic knowledge of C++ so I would not know if I introduced a possible segfault. ;)

### CODE REVIEW

**Comment by czenker** [comment]
Added a second version that uses dynamic arguments on the `call` function. I like that one much better.

Unfortunately I had to put the body of the `call` method into the header file – otherwise the declaration collides with a template defined in https://github.com/daid/SeriousProton/blob/master/src/scriptInterfaceMagic.h#L230

Maybe someone more familiar with C++ can check if this could be fixed. I'm having trouble even naming the code constructs I see there. ;)

**Comment by amir-arad** [comment]
how about naming it something else? like `apply`?

**Comment by czenker** [comment]
> how about naming it something else? like `apply`?

:smile: Yeah that might avoid the collision. But I fear the templates and their names are there for a reason I don't understand. The file is called `magic` after all. :fireworks: 

Any way - it is too late for me to read more documentation today.

**Comment by daid** [comment]
Well, templates generally need to end up in headers anyhow. So this looks proper.

**Comment by JordanLongstaff** [comment]
The <long> and <int> templates need to be added to scriptInterfaceMagic.h. Without them I get build errors.

**Pull request merged**
