### PR TITLE
Support multiple types of return values

### PR DESCRIPTION
**Pull request by gcask**
Supporting multiple types of return values (only a select few, trivial types and strings).
Maintained "legacy behavior" with the no-template function.

Leveraging std.optional now that it's there to gracefully handle nulls.

cc @StarryWisdom

### CODE REVIEW

**Comment by daid** [comment]
Got conflicts here now, most likely because both pull request did something with lineends/spaces/tabs

**Comment by daid** [comment]
Not sure if I like the `call_` function name. I see why you did it... but maybe we should just remove the legacy call and fix all instances to the call() to use the new std::optional return?

**Comment by gcask** [comment]
Sure.

I'm generally trying to minimize changes that would break EE's compilation as much as I can but if you're OK with shifting everything over to `std.optional`, can do.

**Comment by daid** [comment]
I'm fine with two pull requests that are related and need to be merged together for internal API changes.

**Comment by gcask** [comment]
Sister EE change: daid/EmptyEpsilon#1411

**Pull request merged**
