### PR TITLE
Fixed crash when user tries to connect with wrong version.

### PR DESCRIPTION
**Pull request by JonathanILevi**
Fixed crash caused when server refuses a client.

Basically the server tried to disconnect the client but did not remove it from its list of clients.
The crash was specifically caused because SFML will crash if you try to disconnect a socket in a SocketSelector.

### CODE REVIEW

**Comment by JonathanILevi** [comment]
@daid This is a friendly notification in case you did not already get notified.

**Comment by daid** [comment]
Which version of SFML are you using? And on which OS? As this sounds more like a bug in SFML.

What should happen, is that the disconnect causes the receive call (which is in a loop) to return that the socket is disconnected:
https://github.com/daid/SeriousProton/blob/master/src/multiplayer_server.cpp#L184
At which point this code should trigger:
https://github.com/daid/SeriousProton/blob/master/src/multiplayer_server.cpp#L264

**Comment by JonathanILevi** [comment]
I am on a Linux rig.  

When the client gets disconnected before being authenticated shouldn't the call to `onDisconnectClient` be skipped since the call to `handleNewClient` never happened?

This bug is an old bug, and very important to the players on the USN, we have suffered many a game ended prematurely because of a misversioned client joining mid game.

I'll do some more specific testing and get a bug filed with SFML if it is their bug.

**Comment by daid** [comment]
The onDisconnectClient only does some bookkeeping, you are right that's it's not correct that it's called. But it also shouldn't cause any issues.

I still see why it does wrong, I remove a socket from the selector after closing the socket. SFML doesn't check for this, and most likely that's where it goes wrong. Even if SFML would check for it, there is no correct way to remove it from the selector at that point anymore. So it needs to be removed before disconnecting.

I think I have a slighly cleaner patch.

**Pull request closed without merging**
