### PR TITLE
Permissions for HTTP-requests pull

### PR DESCRIPTION
**Pull request by vslotman**
Since the HTTP-server leaves the game wide open, I've added IP-filtering and permissions to the HTTP-server. 
An incomming connection gets granted a certain permission based on its IPv4-address, which get checked both literal and using *-wildcards. 
COnnections which do not have permission get dropped.

### CODE REVIEW

**Comment by daid** [comment]
I think this is overkill for the intended goal for the httpserver in SP. It's intention is to be a simple http server to server some internal data from games. And this is making it more complex then needed.

A simple IP filtering on incoming connections would be enough, no need to set permissions per IP mask and stuff like that. Especially because the permissions don't do anything here and suddenly need to be implemented by HttpRequestHandlers. Which adds added complexity over there.


(Also, conflicts with your other pull request, includes the #define sFALSE again, as well as some debug code)

**Comment by vslotman** [comment]
I've simplified the permissions to a simple IP-based filter, and removed the sFALS define.

**Comment by daid** [comment]
Small thing, line 84, assumes the IP and the filter always have 4 sections after splitting on dots. While for the IP from the connection this is always true (as SFML only does IPv4), but the "filterIp" is given from user configuration and it's not checked if it was a proper IP address.

**Comment by vslotman** [comment]
I've added some size-checking for the IP-address. 

Github started complaining about merge-issues, so I ended up having to do a full merge with daid/master...

**Pull request closed without merging**
